---
- name: Pull and run the Rancher/server container
  docker_container:
    name: "{{ rancher_container_name }}"
    image: rancher/server
    restart_policy: always
    ports: 
      - "{{ rancher_port }}:8080"

- name: Wait for the Rancher server to start
  action: command docker logs {{ rancher_container_name }}
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 30
  delay: 10
