---
- name: Install dependencies
  apt: 
      name={{ item }} 
      update_cache=yes
  with_items: 
      - python-dev
      - python-setuptools

- name: Install pip
  easy_install: 
      name=pip 

- name: Uninstall docker-py
  pip: 
      name=docker-py
      state=absent

- name: Install docker
  pip: 
      name=docker
      state=present
